import "../entity-rows/hui-event-entity-row";
import "../entity-rows/hui-media-player-entity-row";
import "../entity-rows/hui-scene-entity-row";
import "../entity-rows/hui-script-entity-row";
import "../entity-rows/hui-sensor-entity-row";
import "../entity-rows/hui-simple-entity-row";
import "../entity-rows/hui-toggle-entity-row";
import { LovelaceRowConfig } from "../entity-rows/types";
import "../special-rows/hui-attribute-row";
import "../special-rows/hui-button-row";
import "../special-rows/hui-call-service-row";
export declare const createRowElement: (config: LovelaceRowConfig) => import("../cards/hui-error-card").HuiErrorCard | import("../entity-rows/types").LovelaceRow;
export declare const getRowElementClass: (type: string) => Promise<import("../types").LovelaceRowConstructor>;
