import { HassEntity } from "home-assistant-js-websocket";
export declare const FIXED_DOMAIN_STATES: {
    readonly alarm_control_panel: readonly ["armed_away", "armed_custom_bypass", "armed_home", "armed_night", "armed_vacation", "arming", "disarmed", "disarming", "pending", "triggered"];
    readonly automation: readonly ["on", "off"];
    readonly binary_sensor: readonly ["on", "off"];
    readonly button: readonly [];
    readonly calendar: readonly ["on", "off"];
    readonly camera: readonly ["idle", "recording", "streaming"];
    readonly cover: readonly ["closed", "closing", "open", "opening"];
    readonly device_tracker: readonly ["home", "not_home"];
    readonly fan: readonly ["on", "off"];
    readonly humidifier: readonly ["on", "off"];
    readonly input_boolean: readonly ["on", "off"];
    readonly input_button: readonly [];
    readonly lawn_mower: readonly ["error", "paused", "mowing", "docked"];
    readonly light: readonly ["on", "off"];
    readonly lock: readonly ["jammed", "locked", "locking", "unlocked", "unlocking"];
    readonly media_player: readonly ["off", "on", "idle", "playing", "paused", "standby", "buffering"];
    readonly person: readonly ["home", "not_home"];
    readonly plant: readonly ["ok", "problem"];
    readonly remote: readonly ["on", "off"];
    readonly scene: readonly [];
    readonly schedule: readonly ["on", "off"];
    readonly script: readonly ["on", "off"];
    readonly siren: readonly ["on", "off"];
    readonly sun: readonly ["above_horizon", "below_horizon"];
    readonly switch: readonly ["on", "off"];
    readonly timer: readonly ["active", "idle", "paused"];
    readonly update: readonly ["on", "off"];
    readonly vacuum: readonly ["cleaning", "docked", "error", "idle", "paused", "returning"];
    readonly valve: readonly ["closed", "closing", "open", "opening"];
    readonly weather: readonly ["clear-night", "cloudy", "exceptional", "fog", "hail", "lightning-rainy", "lightning", "partlycloudy", "pouring", "rainy", "snowy-rainy", "snowy", "sunny", "windy-variant", "windy"];
};
export declare const getStates: (state: HassEntity, attribute?: string | undefined) => string[];
