import { HassEntity } from "home-assistant-js-websocket";
import { HomeAssistant } from "../types";
export default class MediaPlayerEntity {
    hass: HomeAssistant;
    stateObj: HassEntity;
    private _attr;
    constructor(hass: HomeAssistant, stateObj: HassEntity);
    get isOff(): boolean;
    get isIdle(): boolean;
    get isMuted(): any;
    get isPaused(): boolean;
    get isPlaying(): boolean;
    get isMusic(): boolean;
    get isTVShow(): boolean;
    get hasMediaControl(): boolean;
    get volumeSliderValue(): number;
    get showProgress(): boolean;
    get currentProgress(): any;
    get supportsPause(): boolean;
    get supportsVolumeSet(): boolean;
    get supportsVolumeMute(): boolean;
    get supportsPreviousTrack(): boolean;
    get supportsNextTrack(): boolean;
    get supportsTurnOn(): boolean;
    get supportsTurnOff(): boolean;
    get supportsPlayMedia(): boolean;
    get supportsVolumeButtons(): boolean;
    get supportsSelectSource(): boolean;
    get supportsSelectSoundMode(): boolean;
    get supportsPlay(): boolean;
    get primaryTitle(): string;
    get secondaryTitle(): any;
    get source(): any;
    get sourceList(): any;
    get soundMode(): any;
    get soundModeList(): any;
    mediaPlayPause(): void;
    nextTrack(): void;
    playbackControl(): void;
    previousTrack(): void;
    setVolume(volume: any): void;
    togglePower(): void;
    turnOff(): void;
    turnOn(): void;
    volumeDown(): void;
    volumeMute(mute: any): void;
    volumeUp(): void;
    selectSource(source: any): void;
    selectSoundMode(soundMode: any): void;
    callService(service: any, data?: any): void;
}
