export declare const DEFAULT_PRIMARY_COLOR: "#03a9f4";
export declare const DEFAULT_ACCENT_COLOR: "#ff9800";
export declare const darkStyles: {
    readonly "primary-background-color": "#111111";
    readonly "card-background-color": "#1c1c1c";
    readonly "secondary-background-color": "#282828";
    readonly "clear-background-color": "#111111";
    readonly "primary-text-color": "#e1e1e1";
    readonly "secondary-text-color": "#9b9b9b";
    readonly "disabled-text-color": "#6f6f6f";
    readonly "app-header-text-color": "#e1e1e1";
    readonly "app-header-background-color": "#101e24";
    readonly "switch-unchecked-button-color": "#999999";
    readonly "switch-unchecked-track-color": "#9b9b9b";
    readonly "divider-color": "rgba(225, 225, 225, .12)";
    readonly "outline-color": "rgba(225, 225, 225, .12)";
    readonly "outline-hover-color": "rgba(225, 225, 225, .24)";
    readonly "mdc-ripple-color": "#AAAAAA";
    readonly "mdc-linear-progress-buffer-color": "rgba(255, 255, 255, 0.1)";
    readonly "input-idle-line-color": "rgba(255, 255, 255, 0.42)";
    readonly "input-hover-line-color": "rgba(255, 255, 255, 0.87)";
    readonly "input-disabled-line-color": "rgba(255, 255, 255, 0.06)";
    readonly "input-outlined-idle-border-color": "rgba(255, 255, 255, 0.38)";
    readonly "input-outlined-hover-border-color": "rgba(255, 255, 255, 0.87)";
    readonly "input-outlined-disabled-border-color": "rgba(255, 255, 255, 0.06)";
    readonly "input-fill-color": "rgba(255, 255, 255, 0.05)";
    readonly "input-disabled-fill-color": "rgba(255, 255, 255, 0.02)";
    readonly "input-ink-color": "rgba(255, 255, 255, 0.87)";
    readonly "input-label-ink-color": "rgba(255, 255, 255, 0.6)";
    readonly "input-disabled-ink-color": "rgba(255, 255, 255, 0.37)";
    readonly "input-dropdown-icon-color": "rgba(255, 255, 255, 0.54)";
    readonly "codemirror-keyword": "#C792EA";
    readonly "codemirror-operator": "#89DDFF";
    readonly "codemirror-variable": "#f07178";
    readonly "codemirror-variable-2": "#EEFFFF";
    readonly "codemirror-variable-3": "#DECB6B";
    readonly "codemirror-builtin": "#FFCB6B";
    readonly "codemirror-atom": "#F78C6C";
    readonly "codemirror-number": "#FF5370";
    readonly "codemirror-def": "#82AAFF";
    readonly "codemirror-string": "#C3E88D";
    readonly "codemirror-string-2": "#f07178";
    readonly "codemirror-comment": "#545454";
    readonly "codemirror-tag": "#FF5370";
    readonly "codemirror-meta": "#FFCB6B";
    readonly "codemirror-attribute": "#C792EA";
    readonly "codemirror-property": "#C792EA";
    readonly "codemirror-qualifier": "#DECB6B";
    readonly "codemirror-type": "#DECB6B";
    readonly "energy-grid-return-color": "#a280db";
    readonly "map-filter": "invert(.9) hue-rotate(170deg) brightness(1.5) contrast(1.2) saturate(.3)";
    readonly "disabled-color": "#464646";
};
export declare const derivedStyles: {
    readonly "state-icon-error-color": "var(--error-state-color, var(--error-color))";
    readonly "state-unavailable-color": "var(--state-icon-unavailable-color, var(--disabled-text-color))";
    readonly "sidebar-text-color": "var(--primary-text-color)";
    readonly "sidebar-background-color": "var(--card-background-color)";
    readonly "sidebar-selected-text-color": "var(--primary-color)";
    readonly "sidebar-selected-icon-color": "var(--primary-color)";
    readonly "sidebar-icon-color": "rgba(var(--rgb-primary-text-color), 0.6)";
    readonly "switch-checked-color": "var(--primary-color)";
    readonly "switch-checked-button-color": "var(--switch-checked-color, var(--primary-background-color))";
    readonly "switch-checked-track-color": "var(--switch-checked-color, #000000)";
    readonly "switch-unchecked-button-color": "var(--switch-unchecked-color, var(--primary-background-color))";
    readonly "switch-unchecked-track-color": "var(--switch-unchecked-color, #000000)";
    readonly "slider-color": "var(--primary-color)";
    readonly "slider-secondary-color": "var(--light-primary-color)";
    readonly "slider-track-color": "var(--scrollbar-thumb-color)";
    readonly "label-badge-background-color": "var(--card-background-color)";
    readonly "label-badge-text-color": "rgba(var(--rgb-primary-text-color), 0.8)";
    readonly "paper-listbox-background-color": "var(--card-background-color)";
    readonly "paper-item-icon-color": "var(--state-icon-color)";
    readonly "paper-item-icon-active-color": "var(--state-icon-active-color)";
    readonly "table-header-background-color": "var(--input-fill-color)";
    readonly "table-row-background-color": "var(--primary-background-color)";
    readonly "table-row-alternative-background-color": "var(--secondary-background-color)";
    readonly "data-table-background-color": "var(--card-background-color)";
    readonly "markdown-code-background-color": "var(--primary-background-color)";
    readonly "mdc-theme-primary": "var(--primary-color)";
    readonly "mdc-theme-secondary": "var(--accent-color)";
    readonly "mdc-theme-background": "var(--primary-background-color)";
    readonly "mdc-theme-surface": "var(--card-background-color)";
    readonly "mdc-theme-on-primary": "var(--text-primary-color)";
    readonly "mdc-theme-on-secondary": "var(--text-primary-color)";
    readonly "mdc-theme-on-surface": "var(--primary-text-color)";
    readonly "mdc-theme-text-disabled-on-light": "var(--disabled-text-color)";
    readonly "mdc-theme-text-primary-on-background": "var(--primary-text-color)";
    readonly "mdc-theme-text-secondary-on-background": "var(--secondary-text-color)";
    readonly "mdc-theme-text-hint-on-background": "var(--secondary-text-color)";
    readonly "mdc-theme-text-icon-on-background": "var(--secondary-text-color)";
    readonly "mdc-theme-error": "var(--error-color)";
    readonly "app-header-text-color": "var(--text-primary-color)";
    readonly "app-header-background-color": "var(--primary-color)";
    readonly "mdc-checkbox-unchecked-color": "rgba(var(--rgb-primary-text-color), 0.54)";
    readonly "mdc-checkbox-disabled-color": "var(--disabled-text-color)";
    readonly "mdc-radio-unchecked-color": "rgba(var(--rgb-primary-text-color), 0.54)";
    readonly "mdc-radio-disabled-color": "var(--disabled-text-color)";
    readonly "mdc-tab-text-label-color-default": "var(--primary-text-color)";
    readonly "mdc-button-disabled-ink-color": "var(--disabled-text-color)";
    readonly "mdc-button-outline-color": "var(--outline-color)";
    readonly "mdc-dialog-scroll-divider-color": "var(--divider-color)";
    readonly "mdc-dialog-heading-ink-color": "var(--primary-text-color)";
    readonly "mdc-dialog-content-ink-color": "var(--primary-text-color)";
    readonly "mdc-text-field-idle-line-color": "var(--input-idle-line-color)";
    readonly "mdc-text-field-hover-line-color": "var(--input-hover-line-color)";
    readonly "mdc-text-field-disabled-line-color": "var(--input-disabled-line-color)";
    readonly "mdc-text-field-outlined-idle-border-color": "var(--input-outlined-idle-border-color)";
    readonly "mdc-text-field-outlined-hover-border-color": "var(--input-outlined-hover-border-color)";
    readonly "mdc-text-field-outlined-disabled-border-color": "var(--input-outlined-disabled-border-color)";
    readonly "mdc-text-field-fill-color": "var(--input-fill-color)";
    readonly "mdc-text-field-disabled-fill-color": "var(--input-disabled-fill-color)";
    readonly "mdc-text-field-ink-color": "var(--input-ink-color)";
    readonly "mdc-text-field-label-ink-color": "var(--input-label-ink-color)";
    readonly "mdc-text-field-disabled-ink-color": "var(--input-disabled-ink-color)";
    readonly "mdc-select-idle-line-color": "var(--input-idle-line-color)";
    readonly "mdc-select-hover-line-color": "var(--input-hover-line-color)";
    readonly "mdc-select-outlined-idle-border-color": "var(--input-outlined-idle-border-color)";
    readonly "mdc-select-outlined-hover-border-color": "var(--input-outlined-hover-border-color)";
    readonly "mdc-select-outlined-disabled-border-color": "var(--input-outlined-disabled-border-color)";
    readonly "mdc-select-fill-color": "var(--input-fill-color)";
    readonly "mdc-select-disabled-fill-color": "var(--input-disabled-fill-color)";
    readonly "mdc-select-ink-color": "var(--input-ink-color)";
    readonly "mdc-select-label-ink-color": "var(--input-label-ink-color)";
    readonly "mdc-select-disabled-ink-color": "var(--input-disabled-ink-color)";
    readonly "mdc-select-dropdown-icon-color": "var(--input-dropdown-icon-color)";
    readonly "mdc-select-disabled-dropdown-icon-color": "var(--input-disabled-ink-color)";
    readonly "chip-background-color": "rgba(var(--rgb-primary-text-color), 0.15)";
    readonly "material-body-text-color": "var(--primary-text-color)";
    readonly "material-background-color": "var(--card-background-color)";
    readonly "material-secondary-background-color": "var(--secondary-background-color)";
    readonly "material-secondary-text-color": "var(--secondary-text-color)";
};
